name: Deploy to NCP

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
      
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Build and push Client Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./IMJM-client
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/imjm-client:latest
        
    - name: Build and push Admin Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./IMJM-admin
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/imjm-admin:latest
        
    - name: Build and push Server Docker image
      uses: docker/build-push-action@v4
      with:
        context: ./IMJM-server
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/imjm-server:latest
        
    - name: Deploy to NCP Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.NCP_HOST }}
        username: ${{ secrets.NCP_USERNAME }}
        key: ${{ secrets.NCP_SSH_KEY }}
        script: |
          echo "Starting SSH connection"
          ssh -v root@223.130.150.215  # 여기서 verbose 모드로 SSH 연결 시도
          cd /path/to/deployment
          docker-compose down
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/imjm-client:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/imjm-admin:latest
          docker pull ${{ secrets.DOCKERHUB_USERNAME }}/imjm-server:latest
          export JASYPT_ENCRYPTOR_PASSWORD=${{ secrets.JASYPT_ENCRYPTOR_PASSWORD }}
          docker-compose up -d

